### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wl935** [CeMueller/Financial_Modeling#1]
Hi, could you please provide the dataset that you used in your codes?

**Comment by CeMueller** [comment]
Hey, I uploaded the stock time series (they were retrieved either from Bloomberg or Reuters) and the Fama French Factors (source: http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html)  in the data folder

**Comment by wl935** [comment]
Many thanks for the upload.
